name:          SQL style guide for Ricardo's DI Team adapted from Simon Holywell
description:   A consistent code style guide for SQL to ensure legible and maintainable projects


url:           https://ricardo-ch.github.io/sqlstyle.guide/
domain:        ricardo-ch.github.io
port:          4040

markdown:      kramdown
permalink:     pretty
highlighter:   rouge

kramdown:
    input: GFM
    hard_wrap: false
    toc_levels: "2,3"
    auto_ids: true
    transliterated_header_ids: true
    auto_id_stripping: true

plugins:
    - jekyll-redirect-from
    - jekyll-sitemap

#langs:
    #en:
        #en: English
